### ISSUE TITLE
Sigmastar kernel sources

### ISSUE THREAD

**Issue by fifteenhex** [OpenIPC/openipc-2.1#37]
Hi guys,

I'm trying to archive as many of the sigmastar kernel releases as possible here:
https://github.com/linux-chenxing/linux-ssc325
I think I saw on your SDK archive that you have some versions I don't but it looks like it's non-public now. Would you mind putting the kernel source tarballs somewhere for me?

As there are no public datasheets with registers they are the only way to find things like the hardware irq numbers without lots of painful reverse engineering.

**Comment by ZigFisher** [comment]
Dear friend

We have been seeing your work for a long time and are amazed by it. Thank you very much !
Of course, we are ready to contribute to your research. However, for faster communication, do you have the opportunity to use the Telegram messenger? If there is such a possibility (I really hope) then find me there as @FlyRouter.
Thank you very much and see you soon.
