### ISSUE TITLE
hi3516ev300 majestic

### ISSUE THREAD

**Issue by zWolf-SW** [OpenIPC/openipc-2.1#51]
1. Не работает mirror - при включении в majestic.yaml вообще нет видеопотока
2. Не работает ipeye при отсутствии соединения eth0 (соединение wifi установлено) при старте majestic ошибка: IPEYE: Unable generate TID

**Comment by ZigFisher** [comment]
Откройте пожалуйста заявку в https://github.com/OpenIPC/majestic_issues
