### ISSUE TITLE
Как конфигурировать "Memory tuning"?

### ISSUE THREAD

**Issue by vebmaster** [OpenIPC/openipc-2.1#73]
Здравствуйте.
На странице https://github.com/OpenIPC/openipc-2.1/wiki/Memory-tuning расписано какие модули за что отвечают.
Можете добавить описание того, как можно отключить модули и потом включить их?
Спасибо.

**Comment by ZigFisher** [comment]
Добрый день
Смотрите скрипт /usr/bin/load_hisilicon или вместо hisilicon другое имя вендора, в зависимости от типа вашей платы (_goke, _sigmastar, _xiongmai и т.д.)
Так-же вопросы можете задавать в чат-группах проекта
https://openipc.org/#telegram-chat-groups
